## VabamorfWithBertTagger problem on balanced_and_reference_corpus

This problem appeared when tagging block 10,0 and text with index 310 caused an error.

The error is caused in BertMorphTagger by assert after new morph layer is created and morph layer doesn't have the same number of words as 'words' layer.


bert_morph_tagger2.py: 331-332

        assert len(morph_layer) == len(words_layer), \
        f"Failed to rewrite '{morph_layer.name}' layer tokens to '{words_layer.name}' layer words: {len(morph_layer)} != {len(words_layer)}"

In [1]:
%load_ext autoreload
%autoreload 2

In [8]:
from estnltk.converters import text_to_json, json_to_text
from vabamorfwithberttagger import VabamorfWithBertTagger
from estnltk import Text

In [3]:
text = json_to_text(file='balanced_and_reference_corpus_text_310.json')

text

Text(text='LASNAMÄE Tondi raba oli 10 000 aastat tagasi arktiline laguun saarte vahel, mida praegu tunneme Lasnamäena Asudes täiesti uuenenud kultuurikeskkonnas nagu seda on Lasnamäel paiknevad Kuristiku ja Mustakivi mikrorajoon, on raske ette kujutada, et selles piirkonnas oli inimasustus juba mitu tuhat aastat varem. Enne püsiva inimasustuse tekkimist toimusid olulised muutused nii Lasnamäe maastikus kui ka taimestikus. Suhteliselt varsti pärast jää taandumist Eestist, umbes 10 000 aastat tagasi, kui rannajoon asus mitu kilomeetrit lõunapool praegust Rae raba, asus Lasnamäe kohal mitu sopilise rannajoonega lauget saart. Tondi raba oli algselt kahe saarevaheline laguun. Tondi rabas võisid küttida juba Kunda kultuuri hõimud. Igijääst vabanenud aladel hakkas tärkama elu. Algul valitses karm subarktiline kliima. Sellele vastavalt levis ka polaaraladele iseloomulik taimestik. Seejärel kliima järk-järgult soojenes ning ei ole välistatud, et kahe saare vahelises laguunis käisid kalastamas need need lõuna poolt tulnud kütid ja kalastajastajad, keda kirjanduses nimetatakse Kunda kultuuri hõimudeks. Tondi rabast võetud õietolmuanalüüs näitas, et selles ümbruses kasvas rohkesti kaski. Kohati esines ka mände, jalakaid ja tammi. Pärast Joldiamere taandumist kahanes veepind väga oluliselt ning Tondi raba kohal püsis umbes 9100 - 7800 aastat tagasi järv, mille põhja settis muda. Umbes 7800 aastat tagasi algas järve kinnikasvamine ning sellel kohal hakkas kujunema soo. Sellest ajast on pärit 0,7 meetri paksune tarnapilliroo turbakiht. Umbes 4000 aastat tagasi hakkas soos tekkima tarna- ning umbes 3000 aastat tagasi turbasamblaturvas. Kliimamuutused mõjutasid ka taimestikku. Järve kinnikasvamise ajaks levisid selles piirkonnas peamiselt kuused ja lepad. Tondi turbarabas töötanud Härm Vooglaidi mälestuste järgi tuli paksu turbakihi alt sageli välja küllaltki suure läbimõõduga jässakaid vaigurikkaid puutüvesid ja -juuri. Maaviljelusteks sobivate tingimuste juures (suhteliselt paksem viljakas mullakiht) ulatus inimasustus Kuristiku küla piirkonda juba nooremas pronksiajas (10.-7. saj eKr). Selle ajaga on dateeritud Kuristiku külast leitud labidaspeaga ehtenõel ja vähemalt osa keraamikast. Ka Tondi raba õietolmuanalüüs kinnitas inimmõju järsku kasvu 900. - 800. aastal eKr. Kliima jahenemine soosis üleminekut põllundusele. Kivielamud noorema rauaaja lõpust (3. saj eKr - 1. saj pKr) tõendavad asustuse kasvu Kuristiku küla piirkonnas. Võib arvata, et algselt viljeleti alepõllundust, kuid peagi veenduti, et loopealsetel aladel kahandas taimestiku põletamine huumuskihti ning uus mets kasvas asemele väga vaevarikkalt. Seetõttu asendus alepõllundus söödipõllundusega. Intensiivne põlluviljelus muutis märgatavalt Lasnamäe maastikku. Kõigepealt hävitati suur osa raskesti taastuvast metsast. Tõenäoliselt vähenes ka Kuristiku küla põliselanikkond. Üheks põhjuseks võis olla suure Iru linnuse külgetõmbejõud. Olulisemaks võib pidada asjaolu, et koos pinnavee alanemisega muutusid loopealsed alad põllunduseks vähemsobilikuks. Tallinn tungib peale. Nagu hilisema aja allikad tõendavad, kasutati selle piirkonna alasid ümberkaudsete külade heinamaadena ning osalt ka raiealadena. Taani hindamisraamatus, mis koostati 1219.-1220. aastal, ei mainita omaette küla Tondi rabast idapool. Välistatud ei ole ka see, et järveni ulatus mingi osa Taani hindamisraamatus nimetatud Väo (Uv� tho) külast. Hilisema Kuristiku küla maa-ala läbis keskajal Tallinna sarase piir. Piiri märkis maha Taani kuninganna Margareta korraldusel 13. mail 1265. aastal moodustatud erikomisjon. Üheks piirikiviks oli tänaseni säilinud Mustakivi rändrahn. Maade sunniviisiline võõrandamine riivas paljude ümberkaudsete talupoegade ja maaomanike huve. Erinevad piiride tõlgendused viisid sagedaste konfliktideni, kuid tolleaegseid vaidlusi talletas vaid üks osapool, Tallinna linn ning seetõttu saame vaid oletada, millised olid vastaspoole argumendid. Kirjalikult on säilinud andmed vaid traagiliselt lõppenud konfliktidest. Nii toimus 1486. aastal sealsetel heinamaadel kokkupõrge Lagedi talupoegade, eesotsas Lagedi mõisahärra Hermann Zögega ning linna heinaliste vahel. Kokkupõrge lõppes ühe heinalise surmaga. Keskajal asus Tondi rabast kirde pool tsistertslaste Mihkli kloostrile kuulunud heinamaa. Mihkli nunnakloostri vaidlusi selles piirkonnas mainitakse juba 1286.aastal. Hiljem läks see heinamaa Tallinna gümnaasiumi valdusse. Duntest sai Tondi. Georg Gustav Storci 1838. aasta linnaplaanilt näeme, et Tondi ja Sõjamäe raba taga asunud heinamaad piiras põhjapoolt kubermangu gümnaasiumi õpetajate heinamaa, mida varasemal ajal nimetati professorite heinamaaks. 17. sajandi algul rentis linna Väo mõisa bürgermeister Jobst Duntele, kes ehitas uued hooned ja andis need tasuta linnale. Võimalik, et need hooned olid hilisem Katleri ehk Tondi mõis ning Narva maantee ääres asunud Tondi kõrts. Tondi mõisa, kõrtsi ja raba nimi tulenes just Dunte perekonnanimest. Mõningast segadust tekitas asjaolu, et teine Tondi mõis Tallinnas asus praeguse Tondi tänava ääres. Lasnamäe lamburid Professorite heinamaal. Meeleoluka pildi professorite heinamaal ja Tondi kõrtsis puhkamas käinud haritlaste elust-olust annab Herbert Salu 1978. aastal Lundis ilmunud romaan "Lasnamäe lamburid". Tollal oli haritlaste seas populaarne luuleharrastus. Oluliselt mõjutas kohalike poeetide sõpruskonda ehk Lamburseltsi kuulus saksa luuletaja Paul Fleming, kes 1630. aastatel korduvalt Tallinnas viibis. Luulejatate sõpruskonda kuulus ka teisigi tuntud isikuid, näiteks Tallinna gümnaasiumi kreeka keele professor Reiner Brockmann, kellelt pärinevad ka esimesed trükis ilmunud eestikeelsed luuletused. J. Holmbergi 1689.aasta linnaplaanil näeme Tondi raba taga Lagedile suunduva tee ääres, seega hilisema Kuristiku küla kohal, väikest hoonete rühma, mis on tähistatud nimega "Steinberger Dorff". Arvatavasti elasid selles külas vähemalt osa kuulsatest Lasnamäe kiviraiduritest. Kuigi Põhjasõja-järgsed aastakümned olid Tallinna elus sõjas toibumise ajaks, esineb sellest ajast materjale Tondi kõrtsi kohta, kus tallinlased käisid meelt lahutamas ja mille ümbrusse sõideti grüünetama. 19. sajandi algusest on teada juba täpseid andmeid Kuristiku küla üksikutest taludest.')

In [9]:
text["words"][495:510]

Layer(name='words', attributes=('normalized_form',), spans=SL[Span('Taani', [{'normalized_form': None}]),
Span('hindamisraamatus', [{'normalized_form': None}]),
Span('nimetatud', [{'normalized_form': None}]),
Span('Väo', [{'normalized_form': None}]),
Span('(', [{'normalized_form': None}]),
Span('Uv', [{'normalized_form': None}]),
Span('�', [{'normalized_form': None}]),
Span('tho', [{'normalized_form': None}]),
Span(')', [{'normalized_form': None}]),
Span('külast', [{'normalized_form': None}]),
Span('.', [{'normalized_form': None}]),
Span('Hilisema', [{'normalized_form': None}]),
Span('Kuristiku', [{'normalized_form': None}]),
Span('küla', [{'normalized_form': None}]),
Span('maa-ala', [{'normalized_form': None}])])

In [4]:
tagger = VabamorfWithBertTagger( output_layer="minu_morf", 
                              use_postanalysis=True,
                              correct_verb_annotation=True, 
                              change_to_bert_form=True )

In [7]:
tagger.tag( text )

AssertionError: ("Failed to rewrite 'minu_morf' layer tokens to 'words' layer words: 909 != 910", "in the 'VabamorfWithBertTagger'")

In [5]:
t1 = Text("Välistatud ei ole ka see, et järveni ulatus mingi osa Taani hindamisraamatus nimetatud Väo (Uv� tho) külast. ")
#t1 = Text("Välistatud ei ole ka see, et järveni ulatus mingi osa Taani hindamisraamatus nimetatud Väo (Uv??? tho) külast. ")
t1.tag_layer(["words", "sentences"])

Text(text='Välistatud ei ole ka see, et järveni ulatus mingi osa Taani hindamisraamatus nimetatud Väo (Uv� tho) külast. ')

In [6]:
t1["words"]

Layer(name='words', attributes=('normalized_form',), spans=SL[Span('Välistatud', [{'normalized_form': None}]),
Span('ei', [{'normalized_form': None}]),
Span('ole', [{'normalized_form': None}]),
Span('ka', [{'normalized_form': None}]),
Span('see', [{'normalized_form': None}]),
Span(',', [{'normalized_form': None}]),
Span('et', [{'normalized_form': None}]),
Span('järveni', [{'normalized_form': None}]),
Span('ulatus', [{'normalized_form': None}]),
Span('mingi', [{'normalized_form': None}]),
Span('osa', [{'normalized_form': None}]),
Span('Taani', [{'normalized_form': None}]),
Span('hindamisraamatus', [{'normalized_form': None}]),
Span('nimetatud', [{'normalized_form': None}]),
Span('Väo', [{'normalized_form': None}]),
Span('(', [{'normalized_form': None}]),
Span('Uv', [{'normalized_form': None}]),
Span('�', [{'normalized_form': None}]),
Span('tho', [{'normalized_form': None}]),
Span(')', [{'normalized_form': None}]),
Span('külast', [{'normalized_form': None}]),
Span('.', [{'normalized_form': None}])])

In [7]:
tagger.tag( t1 )

tokens:
 Layer(name='minu_morf', attributes=('bert_tokens', 'form', 'partofspeech', 'probability'), spans=SL[Span('Vä', [{'bert_tokens': '▁Vä', 'form': 'tud', 'partofspeech': 'V', 'probability': 0.99557}]),
Span('list', [{'bert_tokens': 'list', 'form': 'tud', 'partofspeech': 'V', 'probability': 0.99599}]),
Span('atud', [{'bert_tokens': 'atud', 'form': 'tud', 'partofspeech': 'V', 'probability': 0.99727}]),
Span(' ei', [{'bert_tokens': '▁ei', 'form': 'neg', 'partofspeech': 'V', 'probability': 0.99996}]),
Span(' ole', [{'bert_tokens': '▁ole', 'form': 'neg o', 'partofspeech': 'V', 'probability': 0.99992}]),
Span(' ka', [{'bert_tokens': '▁ka', 'form': '', 'partofspeech': 'D', 'probability': 0.99996}]),
Span(' see', [{'bert_tokens': '▁see', 'form': 'sg n', 'partofspeech': 'P', 'probability': 0.99993}]),
Span(',', [{'bert_tokens': ',', 'form': '', 'partofspeech': 'Z', 'probability': 0.99997}]),
Span(' et', [{'bert_tokens': '▁et', 'form': '', 'partofspeech': 'J', 'probability': 0.99994}]),
Span(' järv', [{'bert_tokens': '▁järv', 'form': 'sg ter', 'partofspeech': 'S', 'probability': 0.99867}]),
Span('eni', [{'bert_tokens': 'eni', 'form': 'sg ter', 'partofspeech': 'S', 'probability': 0.99786}]),
Span(' ulatus', [{'bert_tokens': '▁ulatus', 'form': 's', 'partofspeech': 'V', 'probability': 0.99986}]),
Span(' mingi', [{'bert_tokens': '▁mingi', 'form': 'sg n', 'partofspeech': 'P', 'probability': 0.99992}]),
Span(' osa', [{'bert_tokens': '▁osa', 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.9994}]),
Span(' Taani', [{'bert_tokens': '▁Taani', 'form': 'sg g', 'partofspeech': 'H', 'probability': 0.99921}]),
Span(' hindamis', [{'bert_tokens': '▁hindamis', 'form': 'sg in', 'partofspeech': 'S', 'probability': 0.9998}]),
Span('raamatus', [{'bert_tokens': 'raamatus', 'form': 'sg in', 'partofspeech': 'S', 'probability': 0.99981}]),
Span(' nimetatud', [{'bert_tokens': '▁nimetatud', 'form': '', 'partofspeech': 'A', 'probability': 0.9998}]),
Span(' Vä', [{'bert_tokens': '▁Vä', 'form': 'sg g', 'partofspeech': 'H', 'probability': 0.99902}]),
Span('o', [{'bert_tokens': 'o', 'form': 'sg g', 'partofspeech': 'H', 'probability': 0.99899}]),
Span(' (', [{'bert_tokens': '▁(', 'form': '', 'partofspeech': 'Z', 'probability': 0.99989}]),
Span('U', [{'bert_tokens': 'U', 'form': '', 'partofspeech': 'Y', 'probability': 0.70038}]),
Span('v', [{'bert_tokens': 'v', 'form': '', 'partofspeech': 'Y', 'probability': 0.61659}]),
Span(' t', [{'bert_tokens': '▁t', 'form': '', 'partofspeech': 'Y', 'probability': 0.8381}]),
Span('ho', [{'bert_tokens': 'ho', 'form': '', 'partofspeech': 'Y', 'probability': 0.68808}]),
Span(')', [{'bert_tokens': ')', 'form': '', 'partofspeech': 'Z', 'probability': 0.99996}]),
Span(' külast', [{'bert_tokens': '▁külast', 'form': 'sg el', 'partofspeech': 'S', 'probability': 0.99973}]),
Span('.', [{'bert_tokens': '.', 'form': '', 'partofspeech': 'Z', 'probability': 0.99998}])])


morph_layer:
 Layer(name='minu_morf', attributes=('bert_tokens', 'form', 'partofspeech', 'probability'), spans=SL[Span('Välistatud', [{'bert_tokens': ['▁Vä', 'list', 'atud'], 'form': 'tud', 'partofspeech': 'V', 'probability': 0.99557}]),
Span('ei', [{'bert_tokens': ['▁ei'], 'form': 'neg', 'partofspeech': 'V', 'probability': 0.99996}]),
Span('ole', [{'bert_tokens': ['▁ole'], 'form': 'neg o', 'partofspeech': 'V', 'probability': 0.99992}]),
Span('ka', [{'bert_tokens': ['▁ka'], 'form': '', 'partofspeech': 'D', 'probability': 0.99996}]),
Span('see', [{'bert_tokens': ['▁see'], 'form': 'sg n', 'partofspeech': 'P', 'probability': 0.99993}]),
Span(',', [{'bert_tokens': [','], 'form': '', 'partofspeech': 'Z', 'probability': 0.99997}]),
Span('et', [{'bert_tokens': ['▁et'], 'form': '', 'partofspeech': 'J', 'probability': 0.99994}]),
Span('järveni', [{'bert_tokens': ['▁järv', 'eni'], 'form': 'sg ter', 'partofspeech': 'S', 'probability': 0.99867}]),
Span('ulatus', [{'bert_tokens': ['▁ulatus'], 'form': 's', 'partofspeech': 'V', 'probability': 0.99986}]),
Span('mingi', [{'bert_tokens': ['▁mingi'], 'form': 'sg n', 'partofspeech': 'P', 'probability': 0.99992}]),
Span('osa', [{'bert_tokens': ['▁osa'], 'form': 'sg n', 'partofspeech': 'S', 'probability': 0.9994}]),
Span('Taani', [{'bert_tokens': ['▁Taani'], 'form': 'sg g', 'partofspeech': 'H', 'probability': 0.99921}]),
Span('hindamisraamatus', [{'bert_tokens': ['▁hindamis', 'raamatus'], 'form': 'sg in', 'partofspeech': 'S', 'probability': 0.9998}]),
Span('nimetatud', [{'bert_tokens': ['▁nimetatud'], 'form': '', 'partofspeech': 'A', 'probability': 0.9998}]),
Span('Väo', [{'bert_tokens': ['▁Vä', 'o'], 'form': 'sg g', 'partofspeech': 'H', 'probability': 0.99902}]),
Span('(', [{'bert_tokens': ['▁('], 'form': '', 'partofspeech': 'Z', 'probability': 0.99989}]),
Span('Uv', [{'bert_tokens': ['U', 'v'], 'form': '', 'partofspeech': 'Y', 'probability': 0.70038}]),
Span('tho', [{'bert_tokens': ['▁t', 'ho'], 'form': '', 'partofspeech': 'Y', 'probability': 0.8381}]),
Span(')', [{'bert_tokens': [')'], 'form': '', 'partofspeech': 'Z', 'probability': 0.99996}]),
Span('külast', [{'bert_tokens': ['▁külast'], 'form': 'sg el', 'partofspeech': 'S', 'probability': 0.99973}]),
Span('.', [{'bert_tokens': ['.'], 'form': '', 'partofspeech': 'Z', 'probability': 0.99998}])])

AssertionError: ("Failed to rewrite 'minu_morf' layer tokens to 'words' layer words: 21 != 22", "in the 'VabamorfWithBertTagger'")